on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
name: Code Analysis
jobs:
  cli-tests:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      disable_tools: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      #- name: Run Jacoco and Coveralls
      #  run: mvn clean test jacoco:report coveralls:report 
      - name: Run Sonar Analysis
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=clun_astra-cli
      
        
